const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const STORAGE='together-v3-state';
const defaultState={
  onboarded:false, step:0, homeName:'Our home', me:'Alex', partner:'Sam', view:'home', filter:'all', selected:null,
  tasks:[
    {id:1,title:'Buy groceries',icon:'🛒',assignee:'anyone',due:'Today, 20:00',group:'today',completed:false,overdue:false,recurring:false,effort:'Normal'},
    {id:2,title:'Take out the trash',icon:'♲',assignee:'sam',due:'Today',group:'today',completed:false,overdue:false,recurring:true,repeat:'Every 2 days',effort:'Quick',subtasks:['Take out the bins','Bring bins back in']},
    {id:3,title:'Clean the bathroom',icon:'✦',assignee:'alex',due:'Today',group:'today',completed:false,overdue:true,recurring:true,repeat:'Every Sunday',effort:'Medium'},
    {id:4,title:'Laundry',icon:'▣',assignee:'sam',due:'Tomorrow',group:'tomorrow',completed:false,overdue:false,recurring:true,repeat:'Every 3 days',effort:'Normal'},
    {id:5,title:'Water plants',icon:'❧',assignee:'anyone',due:'Tomorrow',group:'tomorrow',completed:false,overdue:false,recurring:true,repeat:'Every 3 days',effort:'Quick'},
    {id:6,title:'Change bed sheets',icon:'▤',assignee:'alex',due:'Thursday',group:'thu',completed:true,overdue:false,recurring:true,repeat:'Every 2 weeks',effort:'Medium'},
    {id:7,title:'Mop floors',icon:'⌁',assignee:'sam',due:'Friday',group:'fri',completed:true,overdue:false,recurring:false,effort:'Medium'}
  ],
  routines:[
    {name:'Cleaning',icon:'✦',count:6},{name:'Kitchen',icon:'♲',count:4},{name:'Laundry',icon:'▣',count:3},{name:'Shopping',icon:'🛒',count:2},{name:'Bathroom',icon:'◌',count:3},{name:'Pets',icon:'♧',count:2},{name:'Plants',icon:'❧',count:2},{name:'Kids',icon:'♙',count:1}
  ],
  routineSelections:['Dishes','Trash','Groceries'],
  notifications:[
    {icon:'🛒',text:'Groceries are due this evening.',time:'2h ago'},
    {icon:'♙',text:'Sam is taking care of the laundry.',time:'3h ago'},
    {icon:'♲',text:'Trash is still unclaimed for tonight.',time:'5h ago'},
    {icon:'✓',text:'Alex completed Clean kitchen.',time:'1d ago'},
    {icon:'▣',text:'New routine added: Change bed sheets.',time:'1d ago'}
  ]
};
let state=load();
if(new URLSearchParams(location.search).get('demo')==='1'){state.onboarded=true;state.step=0;state.view='home';}
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
function set(patch){state={...state,...patch};save();render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nav(){return `<nav class="bottom-nav" aria-label="Main navigation">${[['home','⌂','Home'],['week','▦','Week'],['household','▣','Household'],['us','♙','Us']].map(([v,i,l])=>`<button class="nav-btn ${state.view===v?'active':''}" data-view="${v}"><span class="nav-icon">${i}</span>${l}</button>`).join('')}</nav>`}
function sidebar(){return `<aside class="desktop-sidebar"><div class="brand">Together</div><div class="side-nav">${[['home','⌂','Home'],['week','▦','Week'],['household','▣','Household'],['us','♙','Us']].map(([v,i,l])=>`<button class="side-btn ${state.view===v?'active':''}" data-view="${v}"><span>${i}</span>${l}</button>`).join('')}</div><div class="side-spacer"></div><div class="side-home">${esc(state.homeName)}<br><b>${esc(state.me)} & ${esc(state.partner)}</b></div><div class="install-tip">On iPhone after publishing: Safari → Share → <b>Add to Home Screen</b>.</div></aside>`}
function topbar(extra=''){return `<header class="mobile-top"><div class="brand">Together</div><div class="row gap8">${extra}<div class="avatar-pair"><div class="avatar">A</div><div class="avatar sam">S</div></div></div></header>`}
function appFrame(body, extra=''){return `<div class="app">${sidebar()}<main>${topbar(extra)}<div class="content">${body}</div>${nav()}</main></div>`}
function assignmentLabel(t){if(t.overdue)return '<span class="assignee overdue">Overdue</span>';if(t.assignee==='alex')return '<span class="assignee you">You</span>';if(t.assignee==='sam')return '<span class="assignee">Sam</span>';return '<span class="assignee anyone">Anyone</span>'}
function taskRow(t){return `<div class="task ${t.completed?'completed':''}" data-open-task="${t.id}"><button class="check ${t.completed?'done':''}" data-toggle-task="${t.id}" aria-label="${t.completed?'Mark incomplete':'Complete task'}">${t.completed?'✓':''}</button><div class="task-icon">${t.icon}</div><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.due)}${t.recurring?' · Recurring':''}</div></div>${assignmentLabel(t)}</div>`}
function visibleToday(){let list=state.tasks.filter(t=>t.group==='today');if(state.filter==='mine')list=list.filter(t=>t.assignee==='alex');if(state.filter==='partner')list=list.filter(t=>t.assignee==='sam');if(state.filter==='unassigned')list=list.filter(t=>t.assignee==='anyone');return list}
function home(){const list=visibleToday();const open=list.filter(t=>!t.completed), done=list.filter(t=>t.completed);if(state.tasks.filter(t=>t.group==='today'&&!t.completed).length===0)return emptyState();return appFrame(`<div class="desktop-grid"><section><div class="row between"><div><div class="eyebrow">${esc(state.homeName)}</div><h1 class="screen-title">Good morning, ${esc(state.me)}.</h1><div class="hero-note">${state.tasks.filter(t=>t.group==='today'&&!t.completed).length} things need attention today.</div></div><button class="icon-btn plus" data-add aria-label="Add task">+</button></div><div class="chips">${[['all','All'],['mine','Mine'],['partner','Partner'],['unassigned','Unassigned']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" data-filter="${v}">${l}${v==='all'?' '+state.tasks.filter(t=>t.group==='today'&&!t.completed).length:''}</button>>`).join('')}</div><div class="section"><div class="card task-list">${open.map(taskRow).join('')||'<div class="subtle" style="padding:18px">Nothing here.</div>'}</div>${done.length?`<button class="summary-row" data-show-completed style="border:0;width:100%"><span>Completed today</span><span>${done.length} ›</span></button>`:''}</div></section><aside class="desktop-panel"><div class="card load-card"><div class="section-head"><h2>Shared load</h2><span class="subtle">This week</span></div><div class="load-bar"><div class="load-a"></div><div class="load-b"></div></div><div class="load-labels"><div>52%<small>12 handled</small></div><div style="text-align:right">48%<small>11 handled</small></div></div><p class="subtle" style="text-align:center;margin:16px 0 0"><b style="color:var(--ink)">Looks balanced</b><br>Great teamwork this week.</p></div><div class="card" style="padding:18px;margin-top:16px"><div class="eyebrow">Home note</div><h2 style="margin:8px 0 6px;font-size:20px">A calmer home leads to a brighter you.</h2><p class="subtle" style="margin:0">Keep the focus on what needs attention, not on who is winning.</p></div></aside></div>`)}
function emptyState(){return appFrame(`<div class="row between"><div class="eyebrow">${esc(state.homeName)}</div><button class="icon-btn plus" data-add>+</button></div><div class="empty"><img src="assets/all-caught-up.png" alt="Chair, cat and plant illustration"><h2>All caught up!</h2><p class="subtle">Nothing needs your attention right now.</p><div class="next-up"><div class="next-icon">▣</div><div><div class="subtle">Next up</div><strong>Laundry</strong><div class="subtle">Tomorrow</div></div></div></div>`)}
function week(){const groups=[['Today','today'],['Tomorrow','tomorrow'],['Thursday','thu'],['Friday','fri']];return appFrame(`<div class="row between"><div><h1 class="screen-title">This week</h1><div class="subtle">Sep 21 — Sep 27</div></div><div class="row gap8"><button class="icon-btn">‹</button><button class="icon-btn">›</button></div></div>${groups.map(([label,g])=>{const arr=state.tasks.filter(t=>t.group===g&&!t.completed);if(!arr.length)return'';return `<section class="week-group"><div class="week-label"><span>${label}</span><span>${arr.length}</span></div><div class="week-card">${arr.map(taskRow).join('')}</div></section>`}).join('')}`)}
function household(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Household</h1><p class="subtle">Routines & categories</p></div><button class="icon-btn plus" data-add>+</button></div><div class="section card category-list">${state.routines.map((r,i)=>`<button class="category" data-routine="${i}" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><div class="cat-icon">${r.icon}</div><div><strong>${esc(r.name)}</strong><span>${r.count} routine${r.count===1?'':'s'}</span></div><div>›</div></button>`).join('')}</div>`)}
function us(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Us</h1><p class="subtle">Shared load & settings</p></div><button class="icon-btn" data-notifications>♢</button></div><div class="row" style="justify-content:center;gap:46px;margin:26px 0"><div style="text-align:center"><div class="avatar" style="width:58px;height:58px;font-size:20px">A</div><div style="margin-top:8px;font-size:13px">${esc(state.me)}</div></div><div style="font-size:20px;color:#ff95b5">♥</div><div style="text-align:center"><div class="avatar sam" style="width:58px;height:58px;font-size:20px">S</div><div style="margin-top:8px;font-size:13px">${esc(state.partner)}</div></div></div><div class="card load-card"><div class="section-head"><h2>Shared load</h2><span class="subtle">This week</span></div><div class="load-bar"><div class="load-a"></div><div class="load-b"></div></div><div class="load-labels"><div>52%<small>12 tasks</small></div><div style="text-align:right">48%<small>11 tasks</small></div></div><p class="subtle" style="text-align:center;margin:16px 0 0"><b style="color:var(--ink)">Looks balanced</b><br>Great teamwork this week.</p></div><div class="section card" style="padding:0 16px"><button class="setting-row" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>⌂ &nbsp; Home details</span><span>›</span></button><button class="setting-row" data-notifications style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>♢ &nbsp; Notifications</span><span>›</span></button><button class="setting-row" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>♲ &nbsp; Manage routines</span><span>›</span></button><button class="setting-row" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>♙ &nbsp; Invite partner</span><span>›</span></button><button class="setting-row" data-reset style="width:100%;border:0;background:white;text-align:left;color:#9b3741"><span>↺ &nbsp; Reset demo</span><span>›</span></button></div>`)}
function notifications(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Notifications</h1><p class="subtle">Only the important ones.</p></div><button class="icon-btn" data-view="us">×</button></div><div class="section card">${state.notifications.map((n,i)=>`<div class="notification"><div class="task-icon">${n.icon}</div><div><div style="font-size:13px;line-height:1.35">${esc(n.text)}</div></div><div class="time">${esc(n.time)}</div></div>`).join('')}</div>`)}
function render(){if(!state.onboarded)return renderOnboarding();let body=state.view==='home'?home():state.view==='week'?week():state.view==='household'?household():state.view==='us'?us():notifications();$('#app').innerHTML=body;bind();}
function renderOnboarding(){const steps=[welcomeStep,homeStep,partnerStep,routinesStep];$('#app').innerHTML=steps[state.step]();bindOnboarding()}
function pager(n=0,total=4){return `<div class="pager">${Array.from({length:total},(_,i)=>`<i class="${i===n?'active':''}"></i>`).join('')}</div>`}
function stepbar(n){return `<div class="stepbar">${Array.from({length:3},(_,i)=>`<i class="${i<=n?'active':''}"></i>`).join('')}</div>`}
function welcomeStep(){return `<main class="onboard"><div class="brand">Together</div><div class="onboard-photo"></div><h1>A calmer home,<br>together.</h1><p>See what needs attention, share the load, and spend less time talking about chores.</p>${pager(0)}<button class="primary" data-next>Get started</button><button data-skip style="border:0;background:transparent;margin-top:14px;color:#73768c">I already have an account</button></main>`}
function homeStep(){return `<main class="onboard"><button class="icon-btn" data-prev>‹</button>${stepbar(0)}<h1 style="font-size:34px">Let's set up<br>your home.</h1><p>You can always change these later.</p><label class="form-label" style="color:var(--ink)">Home name</label><input id="home-name" value="${esc(state.homeName)}" class="field" style="background:#f0efff;color:var(--ink);border-color:#dedcf7"><label class="form-label" style="color:var(--ink)">Your name</label><input id="me-name" value="${esc(state.me)}" class="field" style="background:#f0efff;color:var(--ink);border-color:#dedcf7"><button class="primary" data-save-home>Continue</button></main>`}
function partnerStep(){return `<main class="onboard"><button class="icon-btn" data-prev>‹</button>${stepbar(1)}<h1 style="font-size:34px">Who do you share<br>your home with?</h1><p>Invite your partner to join. They'll get their own account and you'll share the same home.</p><div class="onboard-card" style="text-align:center;padding:24px"><div style="font-size:28px">↗</div><div class="subtle" style="margin-top:10px">https://together.app/join/abc123</div></div><button class="secondary" data-copy style="width:100%;background:#17192a;color:white;border:0">Copy link</button><button class="secondary" style="width:100%;margin-top:8px">Share…</button><button class="primary" data-next style="margin-top:auto">Continue</button></main>`}
function routinesStep(){const opts=[['Dishes','◉'],['Trash','♲'],['Laundry','▣'],['Vacuum','⌁'],['Bathroom','✦'],['Bed sheets','▤'],['Groceries','🛒'],['Plants','❧'],['Pets','♧']];return `<main class="onboard"><button class="icon-btn" data-prev>‹</button>${stepbar(2)}<h1 style="font-size:34px">What regularly<br>needs attention?</h1><p>You can add more later.</p><div class="routine-grid">${opts.map(([n,i])=>`<button class="routine-opt ${state.routineSelections.includes(n)?'active':''}" data-routine-opt="${n}"><span class="big">${i}</span>${n}</button>`).join('')}</div><button class="primary" data-finish>Continue</button></main>`}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>set({view:b.dataset.view}));$$('[data-filter]').forEach(b=>b.onclick=()=>set({filter:b.dataset.filter}));$$('[data-add]').forEach(b=>b.onclick=openAdd);$$('[data-toggle-task]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTask(+b.dataset.toggleTask)});$$('[data-open-task]').forEach(r=>r.onclick=e=>{if(e.target.closest('[data-toggle-task]'))return;openTask(+r.dataset.openTask)});$$('[data-routine]').forEach(r=>r.onclick=()=>openRoutine(+r.dataset.routine));$$('[data-notifications]').forEach(b=>b.onclick=()=>set({view:'notifications'}));const reset=$('[data-reset]');if(reset)reset.onclick=()=>{localStorage.removeItem(STORAGE);state=structuredClone(defaultState);render()};}
function bindOnboarding(){const next=$('[data-next]');if(next)next.onclick=()=>{state.step=Math.min(3,state.step+1);save();render()};const prev=$('[data-prev]');if(prev)prev.onclick=()=>{state.step=Math.max(0,state.step-1);save();render()};const skip=$('[data-skip]');if(skip)skip.onclick=()=>{state.onboarded=true;save();render()};const sh=$('[data-save-home]');if(sh)sh.onclick=()=>{state.homeName=$('#home-name').value.trim()||'Our home';state.me=$('#me-name').value.trim()||'Alex';state.step=2;save();render()};$$('[data-routine-opt]').forEach(b=>b.onclick=()=>{const n=b.dataset.routineOpt;state.routineSelections=state.routineSelections.includes(n)?state.routineSelections.filter(x=>x!==n):[...state.routineSelections,n];save();render()});const fin=$('[data-finish]');if(fin)fin.onclick=()=>{state.onboarded=true;state.view='home';save();render()};const cp=$('[data-copy]');if(cp)cp.onclick=async()=>{try{await navigator.clipboard.writeText('https://together.app/join/abc123');toast('Invite link copied')}catch{toast('Invite link ready to share')}}}
function toggleTask(id){state.tasks=state.tasks.map(t=>t.id===id?{...t,completed:!t.completed,overdue:false}:t);save();render();toast(state.tasks.find(t=>t.id===id).completed?'Done':'Marked as not done')}
function openAdd(){showSheet(`<div class="sheet-head"><button class="close" data-close>×</button><span></span></div><h2>What needs doing?</h2><input id="new-title" class="field" placeholder="e.g. Buy milk" autofocus><label class="form-label">Who?</label><div class="choice-grid" id="who"><button class="choice active" data-who="anyone"><b>✓</b>Anyone</button><button class="choice" data-who="alex"><b>♙</b>Me</button><button class="choice" data-who="sam"><b>♙</b>Partner</button></div><label class="form-label">When?</label><div class="choice-grid" id="when"><button class="choice compact active" data-when="today">Today</button><button class="choice compact" data-when="tomorrow">Tomorrow</button><button class="choice compact" data-when="pick">Pick date</button></div><label class="form-label">Repeat</label><div class="choice-grid"><button class="choice compact active" data-repeat="no">Does not repeat</button><button class="choice compact" data-repeat="weekly">Weekly</button><button class="choice compact" data-repeat="custom">Custom</button></div><button class="primary" data-create>Add task</button>`);let who='anyone',when='today',repeat='no';$$('[data-who]').forEach(b=>b.onclick=()=>{who=b.dataset.who;activateGroup('#who',b)});$$('[data-when]').forEach(b=>b.onclick=()=>{when=b.dataset.when;activateGroup('#when',b)});$$('[data-repeat]').forEach(b=>b.onclick=()=>{repeat=b.dataset.repeat;$$('[data-repeat]').forEach(x=>x.classList.toggle('active',x===b))});$('[data-create]').onclick=()=>{const title=$('#new-title').value.trim();if(!title)return toast('Add a task name');const id=Math.max(...state.tasks.map(t=>t.id))+1;state.tasks.push({id,title,icon:'✦',assignee:who,due:when==='today'?'Today':when==='tomorrow'?'Tomorrow':'Upcoming',group:when==='tomorrow'?'tomorrow':'today',completed:false,overdue:false,recurring:repeat!=='no',repeat:repeat==='weekly'?'Every week':repeat==='custom'?'Custom':'',effort:'Normal'});save();closeSheet();render();toast('Task added')}}
function activateGroup(sel,b){$$(sel+' .choice').forEach(x=>x.classList.toggle('active',x===b))}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;showSheet(`<div class="sheet-head"><button class="close" data-close>‹</button><button class="close" data-delete="${t.id}">•••</button></div><div class="detail-icon">${t.icon}</div><div class="detail-title">${esc(t.title)}</div><div class="row" style="justify-content:center;gap:7px;margin-bottom:14px"><span class="chip" style="background:#30344a;color:#d8d9e5">Household</span>${t.recurring?'<span class="chip" style="background:#30344a;color:#d8d9e5">↻ Recurring</span>':''}</div><p class="detail-desc">Keep this chore visible without turning it into a competition.</p><div><div class="detail-row"><div><b>Due</b><small>${esc(t.due)}</small></div><span>›</span></div><div class="detail-row"><div><b>Repeats</b><small>${esc(t.repeat||'Does not repeat')}</small></div><span>›</span></div></div><label class="form-label">Assigned to</label><div class="choice-grid" id="assign"><button class="choice ${t.assignee==='alex'?'active':''}" data-assign="alex"><b>A</b>You</button><button class="choice ${t.assignee==='sam'?'active':''}" data-assign="sam"><b>S</b>Sam</button><button class="choice ${t.assignee==='anyone'?'active':''}" data-assign="anyone"><b>＋</b>Anyone</button></div>${t.subtasks?.length?`<label class="form-label">Subtasks</label>${t.subtasks.map(s=>`<label class="subtask"><input type="checkbox"> ${esc(s)}</label>`).join('')}`:''}<button class="primary" data-complete-detail>${t.completed?'Mark as not done':'Mark as complete'}</button>`);$$('[data-assign]').forEach(b=>b.onclick=()=>{t.assignee=b.dataset.assign;save();activateGroup('#assign',b);toast('Assignment updated')});$('[data-complete-detail]').onclick=()=>{toggleTask(t.id);closeSheet()};$('[data-delete]').onclick=()=>{if(confirm('Delete this task?')){state.tasks=state.tasks.filter(x=>x.id!==t.id);save();closeSheet();render();toast('Task deleted')}}}
function openRoutine(i){const r=state.routines[i];showSheet(`<div class="sheet-head"><button class="close" data-close>‹</button><button class="close">•••</button></div><div class="detail-icon">${r.icon}</div><div class="detail-title">${esc(r.name==='Cleaning'?'Clean the bathroom':r.name)}</div><div class="row" style="justify-content:center"><span class="chip" style="background:#302b59;color:#cfc9ff">Routine</span></div><div style="margin-top:20px"><div class="detail-row"><div><b>Repeats</b><small>Every Sunday</small></div><span>›</span></div><div class="detail-row"><div><b>Next due</b><small>Sun, Sep 27</small></div><span>›</span></div><div class="detail-row"><div><b>Assigned to</b><small>Anyone</small></div><span>›</span></div><div class="detail-row"><div><b>Effort</b><small>Medium</small></div><span>›</span></div></div><label class="form-label">Notes</label><p style="color:#b8bac9;font-size:13px">Include shower, sink, toilet and floor.</p><button class="primary">Edit routine</button>`)}
function showSheet(html){$('#modal-root').innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true"><div class="grab"></div>${html}</section></div>`;const bd=$('.sheet-backdrop');bd.onclick=e=>{if(e.target===bd)closeSheet()};$$('[data-close]').forEach(b=>b.onclick=closeSheet)}
function closeSheet(){$('#modal-root').innerHTML=''}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
