const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const STORAGE='together-v3-state';
const defaultState={
  onboarded:false, step:0, homeName:'Our home', me:'Alex', partner:'Sam', view:'home', filter:'all', selected:null,
  tasks:[
    {id:1,title:'Buy groceries',icon:'🛒',assignee:'anyone',due:'Today, 20:00',group:'today',completed:false,overdue:false,recurring:false,effort:'Normal'},
    {id:2,title:'Take out the trash',icon:'♲',assignee:'sam',due:'Today',group:'today',completed:false,overdue:false,recurring:true,repeat:'Every 2 days',effort:'Quick',subtasks:['Take out the bins','Bring bins back in']},
    {id:3,title:'Clean the bathroom',icon:'✦',assignee:'alex',due:'Today',group:'today',completed:false,overdue:true,recurring:true,repeat:'Every Sunday',effort:'Medium'},
    {id:4,title:'Laundry',icon:'▣',assignee:'sam',due:'Tomorrow',group:'tomorrow',completed:false,overdue:false,recurring:true,repeat:'Every 3 days',effort:'Normal'},
    {id:5,title:'Water plants',icon:'❧',assignee:'anyone',due:'Tomorrow',group:'tomorrow',completed:false,overdue:false,recurring:true,repeat:'Every 3 days',effort:'Quick'},
    {id:6,title:'Change bed sheets',icon:'▤',assignee:'alex',due:'Thursday',group:'thu',completed:true,overdue:false,recurring:true,repeat:'Every 2 weeks',effort:'Medium'},
    {id:7,title:'Mop floors',icon:'⌁',assignee:'sam',due:'Friday',group:'fri',completed:true,overdue:false,recurring:false,effort:'Medium'}
  ],
  routines:[
    {name:'Cleaning',icon:'✦',count:6},{name:'Kitchen',icon:'♲',count:4},{name:'Laundry',icon:'▣',count:3},{name:'Shopping',icon:'🛒',count:2},{name:'Bathroom',icon:'◌',count:3},{name:'Pets',icon:'♧',count:2},{name:'Plants',icon:'❧',count:2},{name:'Kids',icon:'♙',count:1}
  ],
  routineSelections:['Dishes','Trash','Groceries'],
  notifications:[
    {icon:'🛒',text:'Groceries are due this evening.',time:'2h ago'},
    {icon:'♙',text:'Sam is taking care of the laundry.',time:'3h ago'},
    {icon:'♲',text:'Trash is still unclaimed for tonight.',time:'5h ago'},
    {icon:'✓',text:'Alex completed Clean kitchen.',time:'1d ago'},
    {icon:'▣',text:'New routine added: Change bed sheets.',time:'1d ago'}
  ]
};
let state=load();
if(new URLSearchParams(location.search).get('demo')==='1'){state.onboarded=true;state.step=0;state.view='home';}
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
function set(patch){state={...state,...patch};save();render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function ico(name,cls=''){return `<i data-lucide="${name}" class="${cls}"></i>`}
function drawIcons(){if(window.lucide)window.lucide.createIcons({attrs:{'stroke-width':1.9}})}
function homeScene(){return `<div class="hero-illustration" aria-hidden="true"><svg viewBox="0 0 180 145" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="sofa" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#9B8EFF"/><stop offset="1" stop-color="#6E5DF4"/></linearGradient><linearGradient id="pot" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#DFFF63"/><stop offset="1" stop-color="#BFEA43"/></linearGradient></defs><ellipse cx="92" cy="128" rx="70" ry="10" fill="#6757F6" opacity=".08"/><rect x="28" y="73" width="92" height="39" rx="16" fill="url(#sofa)"/><rect x="19" y="84" width="18" height="31" rx="9" fill="#7565F7"/><rect x="111" y="83" width="18" height="32" rx="9" fill="#6554E9"/><rect x="40" y="64" width="34" height="27" rx="12" fill="#B8AEFF"/><rect x="76" y="64" width="33" height="27" rx="12" fill="#8E80FA"/><ellipse cx="74" cy="93" rx="23" ry="9" fill="#2A2B44" opacity=".84"/><circle cx="89" cy="90" r="8" fill="#2A2B44"/><path d="M84 84l3-6 4 6" fill="#2A2B44"/><rect x="139" y="87" width="18" height="27" rx="6" fill="url(#pot)"/><path d="M148 88c-4-20 5-34 13-42M148 87c-11-15-14-26-10-36M149 78c10-14 17-17 22-17M142 67c-10-8-13-15-12-22" stroke="#547E55" stroke-width="5" stroke-linecap="round"/><path d="M159 45c6-4 12-2 13 0-3 7-9 9-15 6M137 50c-6-6-12-6-14-4 0 7 6 11 12 10M170 60c5-5 9-5 11-3 0 5-4 9-9 9M131 44c-5-6-9-6-11-4 0 5 4 9 9 9" fill="#78A871"/></svg></div>`}
function artTone(name){const x=name.toLowerCase();if(x.includes('clean'))return'violet';if(x.includes('kitchen'))return'sage';if(x.includes('laundry'))return'blue';if(x.includes('shop')||x.includes('grocer'))return'peach';if(x.includes('bath'))return'aqua';if(x.includes('pet'))return'rose';if(x.includes('plant'))return'green';if(x.includes('kid'))return'yellow';return'violet'}
function categoryArtwork(name){const icon=categoryIconName(name);return `<div class="category-art art-${artTone(name)}"><span class="art-blob blob-a"></span><span class="art-blob blob-b"></span><span class="art-surface"></span><div class="art-object">${ico(icon)}</div><span class="art-spark spark-a"></span><span class="art-spark spark-b"></span></div>`}
function taskArtwork(t){const tone=artTone(t.title);return `<div class="detail-cover art-${tone}"><div class="detail-cover-glow"></div><div class="detail-cover-orb">${ico(taskIconName(t))}</div><div class="detail-cover-caption"><span>${t.recurring?'Routine':'Task'}</span><b>${esc(t.effort||'Normal')} effort</b></div></div>`}
function welcomeArtwork(){return `<div class="welcome-art"><div class="welcome-glow welcome-glow-a"></div><div class="welcome-glow welcome-glow-b"></div><div class="welcome-room">${homeScene()}</div><div class="float-tag float-one">${ico('check-circle-2')} Shared</div><div class="float-tag float-two">${ico('heart')} Balanced</div></div>`}
function taskIconName(t){const x=t.title.toLowerCase();if(x.includes('grocer'))return'shopping-cart';if(x.includes('trash'))return'trash-2';if(x.includes('bath'))return'sparkles';if(x.includes('laundry'))return'washing-machine';if(x.includes('plant'))return'sprout';if(x.includes('bed'))return'bed-double';if(x.includes('mop')||x.includes('vacuum'))return'brush-cleaning';return'circle-check-big'}
function categoryIconName(n){const x=n.toLowerCase();if(x.includes('clean'))return'sparkles';if(x.includes('kitchen'))return'cooking-pot';if(x.includes('laundry'))return'washing-machine';if(x.includes('shop'))return'shopping-bag';if(x.includes('bath'))return'bath';if(x.includes('pet'))return'paw-print';if(x.includes('plant'))return'sprout';if(x.includes('kid'))return'baby';return'house'}
function nav(){return `<nav class="bottom-nav" aria-label="Main navigation">${[['home','house','Home'],['week','calendar-days','Week'],['household','archive','Household'],['us','users-round','Us']].map(([v,i,l])=>`<button class="nav-btn ${state.view===v?'active':''}" data-view="${v}"><span class="nav-icon">${ico(i)}</span>${l}</button>`).join('')}</nav>`}
function sidebar(){return `<aside class="desktop-sidebar"><div class="brand">Together</div><div class="side-nav">${[['home','house','Home'],['week','calendar-days','Week'],['household','archive','Household'],['us','users-round','Us']].map(([v,i,l])=>`<button class="side-btn ${state.view===v?'active':''}" data-view="${v}">${ico(i)}${l}</button>`).join('')}</div><div class="side-spacer"></div><div class="side-home">${esc(state.homeName)}<br><b>${esc(state.me)} & ${esc(state.partner)}</b></div><div class="install-tip">On iPhone after publishing: Safari → Share → <b>Add to Home Screen</b>.</div></aside>`}
function topbar(extra=''){return `<header class="mobile-top"><div class="brand">Together</div><div class="row gap8">${extra}<div class="avatar-pair"><div class="avatar">A</div><div class="avatar sam">S</div></div></div></header>`}
function appFrame(body, extra=''){return `<div class="app">${sidebar()}<main>${topbar(extra)}<div class="content">${body}</div>${nav()}</main></div>`}
function assignmentLabel(t){if(t.overdue)return '<span class="assignee overdue">Overdue</span>';if(t.assignee==='alex')return '<span class="assignee you">You</span>';if(t.assignee==='sam')return '<span class="assignee">Sam</span>';return '<span class="assignee anyone">Anyone</span>'}
function taskRow(t){return `<div class="task ${t.completed?'completed':''}" data-open-task="${t.id}"><button class="check ${t.completed?'done':''}" data-toggle-task="${t.id}" aria-label="${t.completed?'Mark incomplete':'Complete task'}">${t.completed?ico('check'):''}</button><div class="task-icon">${ico(taskIconName(t))}</div><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.due)}${t.recurring?' · Recurring':''}</div></div>${assignmentLabel(t)}</div>`}
function visibleToday(){let list=state.tasks.filter(t=>t.group==='today');if(state.filter==='mine')list=list.filter(t=>t.assignee==='alex');if(state.filter==='partner')list=list.filter(t=>t.assignee==='sam');if(state.filter==='unassigned')list=list.filter(t=>t.assignee==='anyone');return list}
function home(){const list=visibleToday();const open=list.filter(t=>!t.completed),done=list.filter(t=>t.completed);if(state.tasks.filter(t=>t.group==='today'&&!t.completed).length===0)return emptyState();const totalOpen=state.tasks.filter(t=>t.group==='today'&&!t.completed).length;return appFrame(`<div class="desktop-grid"><section><div class="row between"><div class="eyebrow">${esc(state.homeName)}</div><button class="icon-btn plus" data-add aria-label="Add task">${ico('plus')}</button></div><div class="home-hero"><div class="hero-copy"><div class="hero-kicker">${ico('sparkles')} Shared home</div><h1>Good morning,<br>${esc(state.me)}.</h1><p>${totalOpen} things need attention today. Everything else can wait.</p></div>${homeScene()}</div><div class="chips">${[['all','All'],['mine','Mine'],['partner','Partner'],['unassigned','Unassigned']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" data-filter="${v}">${l}${v==='all'?' '+totalOpen:''}</button>`).join('')}</div><div class="section" style="margin-top:10px"><div class="task-list">${open.map(taskRow).join('')||'<div class="subtle" style="padding:18px">Nothing here.</div>'}</div>${done.length?`<button class="summary-row" data-show-completed style="border:0;width:100%"><span>Completed today</span><span>${done.length} ›</span></button>`:''}</div></section><aside class="desktop-panel"><div class="card load-card"><div class="section-head"><h2>Shared load</h2><span class="subtle">This week</span></div><div class="load-bar"><div class="load-a"></div><div class="load-b"></div></div><div class="load-labels"><div>52%<small>12 handled</small></div><div style="text-align:right">48%<small>11 handled</small></div></div><p class="subtle" style="text-align:center;margin:16px 0 0"><b style="color:var(--ink)">Looks balanced</b><br>Great teamwork this week.</p></div><div class="card" style="padding:18px;margin-top:16px"><div class="eyebrow">Home note</div><h2 style="margin:8px 0 6px;font-size:20px">A calmer home leads to a brighter you.</h2><p class="subtle" style="margin:0">Keep the focus on what needs attention, not on who is winning.</p></div></aside></div>`)}
function emptyState(){const tomorrow=state.tasks.filter(t=>t.group==='tomorrow'&&!t.completed).slice(0,2);return appFrame(`<div class="row between"><div class="eyebrow">${esc(state.homeName)}</div><button class="icon-btn plus" data-add>${ico('plus')}</button></div><div class="empty"><div class="calm-state"><div class="calm-icon">${ico('sparkles')}</div><h2>Everything’s handled.</h2><p>Your home is clear for tonight. No catching up, no scorekeeping.</p><div class="calm-meta">${ico('check-circle-2')} 7 done today</div></div><div class="tomorrow-block"><div class="tomorrow-head"><h3>Tomorrow</h3><span class="subtle">${tomorrow.length} things</span></div><div class="task-list">${tomorrow.map(taskRow).join('')}</div></div><button class="primary-purple home-add" data-add>${ico('plus')} Add task</button></div>`)}
function week(){const groups=[['Today','today'],['Tomorrow','tomorrow'],['Thursday','thu'],['Friday','fri']];const days=[['Mon','21'],['Tue','22'],['Wed','23'],['Thu','24'],['Fri','25'],['Sat','26'],['Sun','27']];return appFrame(`<div class="row between"><div><h1 class="screen-title">This week</h1><div class="subtle">Sep 21 — Sep 27</div></div><div class="row gap8"><button class="icon-btn">${ico('chevron-left')}</button><button class="icon-btn">${ico('chevron-right')}</button></div></div><div class="week-strip">${days.map(([d,n],i)=>`<div class="day-pill ${i===1?'active':''}">${d}<b>${n}</b></div>`).join('')}</div><div class="week-progress"><div class="progress-ring"><span>72%</span></div><div><strong>Weekly progress</strong><div class="subtle" style="margin-top:4px">Most of the shared work is already handled.</div></div></div>${groups.map(([label,g])=>{const arr=state.tasks.filter(t=>t.group===g&&!t.completed);if(!arr.length)return'';return `<section class="week-group"><div class="week-label"><span>${label}</span><span>${arr.length}</span></div><div class="week-card">${arr.map(taskRow).join('')}</div></section>`}).join('')}`)}
function household(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Household</h1><p class="subtle">Your routines, grouped by the spaces they belong to.</p></div><button class="icon-btn plus" data-add>${ico('plus')}</button></div><div class="household-filter"><button class="mini-tab active">Spaces</button><button class="mini-tab">Routines</button><button class="mini-tab">Categories</button></div><div class="household-grid rich-grid">${state.routines.map((r,i)=>`<button class="house-card rich-house-card" data-routine="${i}">${categoryArtwork(r.name)}<div class="house-card-copy"><strong>${esc(r.name)}</strong><span>${r.count} routine${r.count===1?'':'s'}</span></div><div class="house-arrow">${ico('chevron-right')}</div></button>`).join('')}</div>`)}
function us(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Us</h1><p class="subtle">Shared load, not competition.</p></div><button class="icon-btn" data-notifications>${ico('bell')}</button></div><div class="us-people"><div style="text-align:center"><div class="person-ring"><div>A</div></div><div style="margin-top:8px;font-size:13px"><b>${esc(state.me)}</b><br><span class="subtle">52% · 12 tasks</span></div></div><div class="heart-orb">${ico('heart')}</div><div style="text-align:center"><div class="person-ring samring"><div>S</div></div><div style="margin-top:8px;font-size:13px"><b>${esc(state.partner)}</b><br><span class="subtle">48% · 11 tasks</span></div></div></div><div class="card load-card"><div class="section-head"><h2>Shared load</h2><span class="subtle">This week</span></div><div class="load-bar"><div class="load-a"></div><div class="load-b"></div></div><p class="subtle" style="margin:16px 0 0"><b style="color:var(--ink)">Looks balanced</b><br>You’re keeping things shared without turning home into a scoreboard.</p></div><div class="section card" style="padding:0 16px"><button class="setting-row" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>${ico('house')} &nbsp; Home details</span><span>›</span></button><button class="setting-row" data-notifications style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>${ico('bell')} &nbsp; Notifications</span><span>›</span></button><button class="setting-row" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>${ico('repeat-2')} &nbsp; Manage routines</span><span>›</span></button><button class="setting-row" style="width:100%;border-left:0;border-right:0;border-top:0;background:white;text-align:left"><span>${ico('user-plus')} &nbsp; Invite partner</span><span>›</span></button>${new URLSearchParams(location.search).get('debug')==='1'? `<button class="setting-row" data-reset style="width:100%;border:0;background:white;text-align:left;color:#9b3741"><span>${ico('rotate-ccw')} &nbsp; Reset demo</span><span>›</span></button>` : ''}</div>`)}
function notifications(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Notifications</h1><p class="subtle">Only the important ones.</p></div><button class="icon-btn" data-view="us">×</button></div><div class="section card">${state.notifications.map((n,i)=>`<div class="notification"><div class="task-icon">${n.icon}</div><div><div style="font-size:13px;line-height:1.35">${esc(n.text)}</div></div><div class="time">${esc(n.time)}</div></div>`).join('')}</div>`)}
function render(){if(!state.onboarded)return renderOnboarding();let body=state.view==='home'?home():state.view==='week'?week():state.view==='household'?household():state.view==='us'?us():notifications();$('#app').innerHTML=body;bind();drawIcons();}
function renderOnboarding(){const steps=[welcomeStep,homeStep,partnerStep,routinesStep];$('#app').innerHTML=steps[state.step]();bindOnboarding();drawIcons()}
function pager(n=0,total=4){return `<div class="pager">${Array.from({length:total},(_,i)=>`<i class="${i===n?'active':''}"></i>`).join('')}</div>`}
function stepbar(n){return `<div class="stepbar">${Array.from({length:3},(_,i)=>`<i class="${i<=n?'active':''}"></i>`).join('')}</div>`}
function welcomeStep(){return `<main class="onboard welcome-screen"><div class="row between"><div class="brand">Together</div><span class="welcome-badge">For two</span></div>${welcomeArtwork()}<div class="eyebrow">A calmer way to share a home</div><h1>A calmer home,<br>together.</h1><p>Know what needs attention, who’s handling it, and when you can both stop thinking about chores.</p><div class="welcome-proof"><span>${ico('sparkles')} Clear today</span><span>${ico('users')} Shared load</span><span>${ico('heart')} No scorekeeping</span></div>${pager(0)}<button class="primary" data-next>Get started</button><button data-skip class="text-button">I already have an account</button></main>`}
function homeStep(){return `<main class="onboard setup-screen"><button class="icon-btn" data-prev>${ico('chevron-left')}</button>${stepbar(0)}<div class="setup-symbol">${ico('house-heart')}</div><div class="eyebrow">Your shared space</div><h1 style="font-size:36px">Let’s set up<br>your home.</h1><p>Keep it simple. You can change names, routines and responsibilities later.</p><div class="form-stack"><label class="form-label" style="color:var(--ink)">Home name</label><div class="input-shell">${ico('house')}<input id="home-name" value="${esc(state.homeName)}" class="field"></div><label class="form-label" style="color:var(--ink)">Your name</label><div class="input-shell">${ico('user-round')}<input id="me-name" value="${esc(state.me)}" class="field"></div></div><button class="primary" data-save-home>Continue</button></main>`}
function partnerStep(){return `<main class="onboard partner-screen"><button class="icon-btn" data-prev>${ico('chevron-left')}</button>${stepbar(1)}<div class="pair-visual"><div class="pair-avatar pair-a">A</div><div class="pair-link">${ico('link-2')}</div><div class="pair-avatar pair-s">S</div></div><div class="eyebrow">Invite your person</div><h1 style="font-size:36px">Who do you share<br>your home with?</h1><p>They’ll join the same household and see the same responsibilities — without either of you becoming the manager.</p><div class="invite-card"><div class="invite-icon">${ico('link-2')}</div><div><b>Private invite link</b><span>together.app/join/abc123</span></div></div><button class="secondary dark-secondary" data-copy style="width:100%">${ico('copy')} Copy invite link</button><button class="secondary" style="width:100%;margin-top:9px">${ico('share-2')} Share…</button><button class="primary" data-next style="margin-top:auto">Continue</button></main>`}
function routinesStep(){const opts=[['Dishes','circle-dot'],['Trash','trash-2'],['Laundry','washing-machine'],['Vacuum','brush-cleaning'],['Bathroom','bath'],['Bed sheets','bed-double'],['Groceries','shopping-cart'],['Plants','sprout'],['Pets','paw-print']];return `<main class="onboard"><button class="icon-btn" data-prev>${ico('chevron-left')}</button>${stepbar(2)}<div class="eyebrow">Starter routines</div><h1 style="font-size:34px">What regularly<br>needs attention?</h1><p>Pick a few to start. You can change everything later.</p><div class="routine-grid">${opts.map(([n,i])=>`<button class="routine-opt ${state.routineSelections.includes(n)?'active':''}" data-routine-opt="${n}"><span class="big">${ico(i)}</span>${n}</button>`).join('')}</div><button class="primary" data-finish>Continue</button></main>`}
function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>set({view:b.dataset.view}));$$('[data-filter]').forEach(b=>b.onclick=()=>set({filter:b.dataset.filter}));$$('[data-add]').forEach(b=>b.onclick=openAdd);$$('[data-toggle-task]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTask(+b.dataset.toggleTask)});$$('[data-open-task]').forEach(r=>r.onclick=e=>{if(e.target.closest('[data-toggle-task]'))return;openTask(+r.dataset.openTask)});$$('[data-routine]').forEach(r=>r.onclick=()=>openRoutine(+r.dataset.routine));$$('[data-notifications]').forEach(b=>b.onclick=()=>set({view:'notifications'}));const reset=$('[data-reset]');if(reset)reset.onclick=()=>{localStorage.removeItem(STORAGE);state=structuredClone(defaultState);render()};}
function bindOnboarding(){const next=$('[data-next]');if(next)next.onclick=()=>{state.step=Math.min(3,state.step+1);save();render()};const prev=$('[data-prev]');if(prev)prev.onclick=()=>{state.step=Math.max(0,state.step-1);save();render()};const skip=$('[data-skip]');if(skip)skip.onclick=()=>{state.onboarded=true;save();render()};const sh=$('[data-save-home]');if(sh)sh.onclick=()=>{state.homeName=$('#home-name').value.trim()||'Our home';state.me=$('#me-name').value.trim()||'Alex';state.step=2;save();render()};$$('[data-routine-opt]').forEach(b=>b.onclick=()=>{const n=b.dataset.routineOpt;state.routineSelections=state.routineSelections.includes(n)?state.routineSelections.filter(x=>x!==n):[...state.routineSelections,n];save();render()});const fin=$('[data-finish]');if(fin)fin.onclick=()=>{state.onboarded=true;state.view='home';save();render()};const cp=$('[data-copy]');if(cp)cp.onclick=async()=>{try{await navigator.clipboard.writeText('https://together.app/join/abc123');toast('Invite link copied')}catch{toast('Invite link ready to share')}}}
function toggleTask(id){state.tasks=state.tasks.map(t=>t.id===id?{...t,completed:!t.completed,overdue:false}:t);save();render();toast(state.tasks.find(t=>t.id===id).completed?'Done':'Marked as not done')}
function openAdd(){showSheet(`<div class="sheet-head"><button class="close" data-close>×</button><span></span></div><h2>What needs doing?</h2><input id="new-title" class="field" placeholder="e.g. Buy milk" autofocus><label class="form-label">Who?</label><div class="choice-grid" id="who"><button class="choice active" data-who="anyone"><b>✓</b>Anyone</button><button class="choice" data-who="alex"><b>♙</b>Me</button><button class="choice" data-who="sam"><b>♙</b>Partner</button></div><label class="form-label">When?</label><div class="choice-grid" id="when"><button class="choice compact active" data-when="today">Today</button><button class="choice compact" data-when="tomorrow">Tomorrow</button><button class="choice compact" data-when="pick">Pick date</button></div><label class="form-label">Repeat</label><div class="choice-grid"><button class="choice compact active" data-repeat="no">Does not repeat</button><button class="choice compact" data-repeat="weekly">Weekly</button><button class="choice compact" data-repeat="custom">Custom</button></div><button class="primary" data-create>Add task</button>`);let who='anyone',when='today',repeat='no';$$('[data-who]').forEach(b=>b.onclick=()=>{who=b.dataset.who;activateGroup('#who',b)});$$('[data-when]').forEach(b=>b.onclick=()=>{when=b.dataset.when;activateGroup('#when',b)});$$('[data-repeat]').forEach(b=>b.onclick=()=>{repeat=b.dataset.repeat;$$('[data-repeat]').forEach(x=>x.classList.toggle('active',x===b))});$('[data-create]').onclick=()=>{const title=$('#new-title').value.trim();if(!title)return toast('Add a task name');const id=Math.max(...state.tasks.map(t=>t.id))+1;state.tasks.push({id,title,icon:'✦',assignee:who,due:when==='today'?'Today':when==='tomorrow'?'Tomorrow':'Upcoming',group:when==='tomorrow'?'tomorrow':'today',completed:false,overdue:false,recurring:repeat!=='no',repeat:repeat==='weekly'?'Every week':repeat==='custom'?'Custom':'',effort:'Normal'});save();closeSheet();render();toast('Task added')}}
function activateGroup(sel,b){$$(sel+' .choice').forEach(x=>x.classList.toggle('active',x===b))}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;showSheet(`<div class="sheet-head floating-sheet-head"><button class="close" data-close>${ico('chevron-left')}</button><button class="close" data-delete="${t.id}">${ico('more-horizontal')}</button></div>${taskArtwork(t)}<div class="detail-content"><div class="detail-title">${esc(t.title)}</div><div class="detail-pills"><span class="detail-pill">${ico('house')} Household</span>${t.recurring?'<span class="detail-pill">'+ico('repeat-2')+' Recurring</span>':''}</div><p class="detail-desc">Keep this visible, easy to claim, and easy to finish.</p><div class="detail-group"><div class="detail-row"><div class="detail-row-icon">${ico('calendar-days')}</div><div class="detail-row-copy"><b>Due</b><small>${esc(t.due)}</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('repeat-2')}</div><div class="detail-row-copy"><b>Repeats</b><small>${esc(t.repeat||'Does not repeat')}</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('gauge')}</div><div class="detail-row-copy"><b>Effort</b><small>${esc(t.effort||'Normal')}</small></div><span>${ico('chevron-right')}</span></div></div><label class="form-label">Assigned to</label><div class="choice-grid" id="assign"><button class="choice ${t.assignee==='alex'?'active':''}" data-assign="alex"><b>A</b>You</button><button class="choice ${t.assignee==='sam'?'active':''}" data-assign="sam"><b>S</b>Sam</button><button class="choice ${t.assignee==='anyone'?'active':''}" data-assign="anyone"><b>${ico('users')}</b>Anyone</button></div>${t.subtasks?.length?`<label class="form-label">Subtasks</label><div class="subtask-card">${t.subtasks.map(s=>`<label class="subtask"><input type="checkbox"> <span>${esc(s)}</span></label>`).join('')}</div>`:''}<div class="detail-cta-row"><button class="secondary snooze-btn">${ico('clock-3')} Snooze</button><button class="primary" data-complete-detail>${ico(t.completed?'rotate-ccw':'check')} ${t.completed?'Mark as not done':'Mark as complete'}</button></div></div>`);$('[data-assign]').forEach(b=>b.onclick=()=>{t.assignee=b.dataset.assign;save();activateGroup('#assign',b);toast('Assignment updated')});$('[data-complete-detail]').onclick=()=>{toggleTask(t.id);closeSheet()};$('[data-delete]').onclick=()=>{if(confirm('Delete this task?')){state.tasks=state.tasks.filter(x=>x.id!==t.id);save();closeSheet();render();toast('Task deleted')}}}
function openRoutine(i){const r=state.routines[i];const pseudo={title:r.name==='Cleaning'?'Clean the bathroom':r.name,effort:'Medium',recurring:true};showSheet(`<div class="sheet-head floating-sheet-head"><button class="close" data-close>${ico('chevron-left')}</button><button class="close">${ico('more-horizontal')}</button></div><div class="detail-cover art-${artTone(r.name)}"><div class="detail-cover-glow"></div><div class="detail-cover-orb">${ico(categoryIconName(r.name))}</div><div class="detail-cover-caption"><span>Routine</span><b>${r.count} in ${esc(r.name)}</b></div></div><div class="detail-content"><div class="detail-title">${esc(pseudo.title)}</div><div class="detail-pills"><span class="detail-pill">${ico('repeat-2')} Routine</span><span class="detail-pill">${ico('sparkles')} ${esc(r.name)}</span></div><div class="detail-group"><div class="detail-row"><div class="detail-row-icon">${ico('repeat-2')}</div><div class="detail-row-copy"><b>Repeats</b><small>Every Sunday</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('calendar-days')}</div><div class="detail-row-copy"><b>Next due</b><small>Sun, Sep 27</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('users')}</div><div class="detail-row-copy"><b>Assigned to</b><small>Anyone</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('gauge')}</div><div class="detail-row-copy"><b>Effort</b><small>Medium</small></div><span>${ico('chevron-right')}</span></div></div><div class="notes-card"><span class="subtle">Notes</span><p>Include shower, sink, toilet and floor.</p></div><button class="primary" style="width:100%">${ico('pencil')} Edit routine</button></div>`)}
function showSheet(html){$('#modal-root').innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true"><div class="grab"></div>${html}</section></div>`;const bd=$('.sheet-backdrop');bd.onclick=e=>{if(e.target===bd)closeSheet()};$('[data-close]').forEach(b=>b.onclick=closeSheet);drawIcons()}
function closeSheet(){$('#modal-root').innerHTML=''}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
