const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const STORAGE='together-v3-state';
const defaultState={
  onboarded:false, step:0, homeName:'Наш дом', me:'Алекс', partner:'Сэм', view:'home', filter:'all', selected:null,
  tasks:[
    {id:1,title:'Купить продукты',icon:'🛒',assignee:'anyone',due:'Сегодня, 20:00',group:'today',completed:false,overdue:false,recurring:false,effort:'Обычная'},
    {id:2,title:'Вынести мусор',icon:'♲',assignee:'sam',due:'Сегодня',group:'today',completed:false,overdue:false,recurring:true,repeat:'Каждые 2 дня',effort:'Быстрая',subtasks:['Вынести мусор','Вернуть контейнеры на место']},
    {id:3,title:'Убрать ванную',icon:'✦',assignee:'alex',due:'Сегодня',group:'today',completed:false,overdue:true,recurring:true,repeat:'Каждое воскресенье',effort:'Средняя'},
    {id:4,title:'Стирка',icon:'▣',assignee:'sam',due:'Завтра',group:'tomorrow',completed:false,overdue:false,recurring:true,repeat:'Каждые 3 дня',effort:'Обычная'},
    {id:5,title:'Полить растения',icon:'❧',assignee:'anyone',due:'Завтра',group:'tomorrow',completed:false,overdue:false,recurring:true,repeat:'Каждые 3 дня',effort:'Быстрая'},
    {id:6,title:'Сменить постельное бельё',icon:'▤',assignee:'alex',due:'Четверг',group:'thu',completed:true,overdue:false,recurring:true,repeat:'Каждые 2 недели',effort:'Средняя'},
    {id:7,title:'Помыть полы',icon:'⌁',assignee:'sam',due:'Пятница',group:'fri',completed:true,overdue:false,recurring:false,effort:'Средняя'}
  ],
  routines:[
    {name:'Уборка',icon:'✦',count:6},{name:'Кухня',icon:'♲',count:4},{name:'Стирка',icon:'▣',count:3},{name:'Покупки',icon:'🛒',count:2},{name:'Ванная',icon:'◌',count:3},{name:'Питомцы',icon:'♧',count:2},{name:'Растения',icon:'❧',count:2},{name:'Дети',icon:'♙',count:1}
  ],
  routineSelections:['Посуда','Мусор','Продукты'],
  notifications:[
    {icon:'🛒',text:'Продукты нужно купить сегодня вечером.',time:'2 ч назад'},
    {icon:'♙',text:'Сэм взял на себя стирку.',time:'3 ч назад'},
    {icon:'♲',text:'Мусор на сегодня пока никто не взял.',time:'5 ч назад'},
    {icon:'✓',text:'Алекс закончил уборку кухни.',time:'1 д назад'},
    {icon:'▣',text:'Добавлена новая рутина: сменить постельное бельё.',time:'1d ago'}
  ]
};
let state=load();
function migrateRussianState(){
  const tr={
    'Our home':'Наш дом','Alex':'Алекс','Sam':'Сэм',
    'Buy groceries':'Купить продукты','Take out the trash':'Вынести мусор',
    'Clean the bathroom':'Убрать ванную','Laundry':'Стирка','Water plants':'Полить растения',
    'Change bed sheets':'Сменить постельное бельё','Mop floors':'Помыть полы',
    'Today, 20:00':'Сегодня, 20:00','Today':'Сегодня','Tomorrow':'Завтра','Thursday':'Четверг','Friday':'Пятница',
    'Every 2 days':'Каждые 2 дня','Every Sunday':'Каждое воскресенье','Every 3 days':'Каждые 3 дня',
    'Every 2 weeks':'Каждые 2 недели','Every week':'Каждую неделю',
    'Normal':'Обычная','Quick':'Быстрая','Medium':'Средняя',
    'Cleaning':'Уборка','Kitchen':'Кухня','Shopping':'Покупки','Bathroom':'Ванная',
    'Pets':'Питомцы','Plants':'Растения','Kids':'Дети',
    'Dishes':'Посуда','Trash':'Мусор','Groceries':'Продукты'
  };
  state.homeName=tr[state.homeName]||state.homeName;
  state.me=tr[state.me]||state.me;
  state.partner=tr[state.partner]||state.partner;
  state.tasks=(state.tasks||[]).map(t=>({...t,title:tr[t.title]||t.title,due:tr[t.due]||t.due,repeat:tr[t.repeat]||t.repeat,effort:tr[t.effort]||t.effort,subtasks:(t.subtasks||[]).map(x=>x==='Take out the bins'?'Вынести мусор':x==='Bring bins back in'?'Вернуть контейнеры на место':x)}));
  state.routines=(state.routines||[]).map(r=>({...r,name:tr[r.name]||r.name}));
  state.routineSelections=(state.routineSelections||[]).map(x=>tr[x]||x);
  const noticeTr={
    'Groceries are due this evening.':'Продукты нужно купить сегодня вечером.',
    'Sam is taking care of the laundry.':'Сэм взял на себя стирку.',
    'Trash is still unclaimed for tonight.':'Мусор на сегодня пока никто не взял.',
    'Alex completed Clean kitchen.':'Алекс закончил уборку кухни.',
    'New routine added: Change bed sheets.':'Добавлена новая рутина: сменить постельное бельё.'
  };
  state.notifications=(state.notifications||[]).map(n=>({...n,text:noticeTr[n.text]||n.text,time:n.time==='2h ago'?'2 ч назад':n.time==='3h ago'?'3 ч назад':n.time==='5h ago'?'5 ч назад':n.time==='1d ago'?'1 д назад':n.time}));
}
migrateRussianState();
save();
if(new URLSearchParams(location.search).get('demo')==='1'){state.onboarded=true;state.step=0;state.view='home';}
function load(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
function set(patch){state={...state,...patch};save();render()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function ico(name,cls=''){return `<i data-lucide="${name}" class="${cls}"></i>`}
function drawIcons(){if(window.lucide)window.lucide.createIcons({attrs:{'stroke-width':1.9}})}
function homeScene(){return `<div class="hero-illustration" aria-hidden="true"><svg viewBox="0 0 180 145" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="sofa" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#9B8EFF"/><stop offset="1" stop-color="#6E5DF4"/></linearGradient><linearGradient id="pot" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#DFFF63"/><stop offset="1" stop-color="#BFEA43"/></linearGradient></defs><ellipse cx="92" cy="128" rx="70" ry="10" fill="#6757F6" opacity=".08"/><rect x="28" y="73" width="92" height="39" rx="16" fill="url(#sofa)"/><rect x="19" y="84" width="18" height="31" rx="9" fill="#7565F7"/><rect x="111" y="83" width="18" height="32" rx="9" fill="#6554E9"/><rect x="40" y="64" width="34" height="27" rx="12" fill="#B8AEFF"/><rect x="76" y="64" width="33" height="27" rx="12" fill="#8E80FA"/><ellipse cx="74" cy="93" rx="23" ry="9" fill="#2A2B44" opacity=".84"/><circle cx="89" cy="90" r="8" fill="#2A2B44"/><path d="M84 84l3-6 4 6" fill="#2A2B44"/><rect x="139" y="87" width="18" height="27" rx="6" fill="url(#pot)"/><path d="M148 88c-4-20 5-34 13-42M148 87c-11-15-14-26-10-36M149 78c10-14 17-17 22-17M142 67c-10-8-13-15-12-22" stroke="#547E55" stroke-width="5" stroke-linecap="round"/><path d="M159 45c6-4 12-2 13 0-3 7-9 9-15 6M137 50c-6-6-12-6-14-4 0 7 6 11 12 10M170 60c5-5 9-5 11-3 0 5-4 9-9 9M131 44c-5-6-9-6-11-4 0 5 4 9 9 9" fill="#78A871"/></svg></div>`}
function artTone(name){const x=name.toLowerCase();if(x.includes('clean')||x.includes('уборк'))return'violet';if(x.includes('kitchen')||x.includes('кухн'))return'sage';if(x.includes('laundry')||x.includes('стир'))return'blue';if(x.includes('shop')||x.includes('grocer')||x.includes('покуп')||x.includes('продукт'))return'peach';if(x.includes('bath')||x.includes('ванн'))return'aqua';if(x.includes('pet')||x.includes('питом'))return'rose';if(x.includes('plant')||x.includes('растен'))return'green';if(x.includes('kid')||x.includes('дет'))return'yellow';return'violet'}
function categoryArtwork(name){const icon=categoryIconName(name);return `<div class="category-art art-${artTone(name)}"><span class="art-blob blob-a"></span><span class="art-blob blob-b"></span><span class="art-surface"></span><div class="art-object">${ico(icon)}</div><span class="art-spark spark-a"></span><span class="art-spark spark-b"></span></div>`}
function taskArtwork(t){const tone=artTone(t.title);return `<div class="detail-cover art-${tone}"><div class="detail-cover-glow"></div><div class="detail-cover-orb">${ico(taskIconName(t))}</div><div class="detail-cover-caption"><span>${t.recurring?'Рутина':'Разовое дело'}</span><b>${esc(t.effort||'Обычная')} нагрузка</b></div></div>`}
function welcomeArtwork(){return `<div class="welcome-art"><div class="welcome-glow welcome-glow-a"></div><div class="welcome-glow welcome-glow-b"></div><div class="welcome-room">${homeScene()}</div><div class="float-tag float-one">${ico('check-circle-2')} Вместе</div><div class="float-tag float-two">${ico('heart')} В балансе</div></div>`}
function taskIconName(t){const x=t.title.toLowerCase();if(x.includes('grocer')||x.includes('продукт'))return'shopping-cart';if(x.includes('trash')||x.includes('мусор'))return'trash-2';if(x.includes('bath')||x.includes('ванн'))return'sparkles';if(x.includes('laundry')||x.includes('стир'))return'washing-machine';if(x.includes('plant')||x.includes('растен'))return'sprout';if(x.includes('bed')||x.includes('постел'))return'bed-double';if(x.includes('mop')||x.includes('vacuum')||x.includes('пол'))return'brush-cleaning';return'circle-check-big'}
function categoryIconName(n){const x=n.toLowerCase();if(x.includes('clean')||x.includes('уборк'))return'sparkles';if(x.includes('kitchen')||x.includes('кухн'))return'cooking-pot';if(x.includes('laundry')||x.includes('стир'))return'washing-machine';if(x.includes('shop')||x.includes('покуп'))return'shopping-bag';if(x.includes('bath')||x.includes('ванн'))return'bath';if(x.includes('pet')||x.includes('питом'))return'paw-print';if(x.includes('plant')||x.includes('растен'))return'sprout';if(x.includes('kid')||x.includes('дет'))return'baby';return'house'}
function nav(){return `<nav class="bottom-nav" aria-label="Основная навигация">${[['home','house','Главная'],['week','calendar-days','Неделя'],['household','archive','Дом'],['us','users-round','Мы']].map(([v,i,l])=>`<button class="nav-btn ${state.view===v?'active':''}" data-view="${v}"><span class="nav-icon">${ico(i)}</span>${l}</button>`).join('')}</nav>`}

function sidebar(){return `<aside class="desktop-sidebar"><div class="brand">Together</div><div class="side-nav">${[['home','house','Главная'],['week','calendar-days','Неделя'],['household','archive','Дом'],['us','users-round','Мы']].map(([v,i,l])=>`<button class="side-btn ${state.view===v?'active':''}" data-view="${v}">${ico(i)}${l}</button>`).join('')}</div><div class="side-spacer"></div><div class="side-home">${esc(state.homeName)}<br><b>${esc(state.me)} & ${esc(state.partner)}</b></div><div class="install-tip">На iPhone: Safari → Поделиться → <b>На экран «Домой»</b>.</div></aside>`}

function topbar(extra=''){return `<header class="mobile-top"><div class="brand">Together</div><div class="row gap8">${extra}<div class="avatar-pair"><div class="avatar">А</div><div class="avatar sam">С</div></div></div></header>`}

function appFrame(body, extra=''){return `<div class="app">${sidebar()}<main>${topbar(extra)}<div class="content">${body}</div>${nav()}</main></div>`}
function assignmentLabel(t){if(t.overdue)return '<span class="assignee overdue">Просрочено</span>';if(t.assignee==='alex')return '<span class="assignee you">Вы</span>';if(t.assignee==='sam')return '<span class="assignee">Сэм</span>';return '<span class="assignee anyone">Свободно</span>'}

function taskRow(t){return `<div class="task ${t.completed?'completed':''}" data-open-task="${t.id}"><button class="check ${t.completed?'done':''}" data-toggle-task="${t.id}" aria-label="${t.completed?'Вернуть в работу':'Отметить выполненным'}">${t.completed?ico('check'):''}</button><div class="task-icon">${ico(taskIconName(t))}</div><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(t.due)}${t.recurring?' · Повторяется':''}</div></div>${assignmentLabel(t)}</div>`}

function visibleToday(){let list=state.tasks.filter(t=>t.group==='today');if(state.filter==='mine')list=list.filter(t=>t.assignee==='alex');if(state.filter==='partner')list=list.filter(t=>t.assignee==='sam');if(state.filter==='unassigned')list=list.filter(t=>t.assignee==='anyone');return list}
function home(){const list=visibleToday();const open=list.filter(t=>!t.completed),done=list.filter(t=>t.completed);if(state.tasks.filter(t=>t.group==='today'&&!t.completed).length===0)return emptyState();const totalOpen=state.tasks.filter(t=>t.group==='today'&&!t.completed).length;return appFrame(`<div class="desktop-grid"><section><div class="row between top-context"><div><div class="eyebrow">${esc(state.homeName)}</div><div class="context-line">Сегодня · ${totalOpen} требуют внимания</div></div><button class="icon-btn plus" data-add aria-label="Добавить дело">${ico('plus')}</button></div><div class="home-hero"><div class="hero-copy"><div class="hero-kicker">${ico('sparkles')} Общий дом</div><h1>Доброе утро,<br>${esc(state.me)}.</h1><p>Сегодня есть ${totalOpen} дела, которые требуют внимания. Остальное может подождать.</p></div>${homeScene()}</div><div class="chips">${[['all','Все'],['mine','Мои'],['partner','Партнёра'],['unassigned','Свободные']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" data-filter="${v}">${l}${v==='all'?' '+totalOpen:''}</button>`).join('')}</div><div class="section today-section"><div class="section-head compact-head"><h2>Сегодня</h2><span class="subtle">${open.length} осталось</span></div><div class="task-list">${open.map(taskRow).join('')||'<div class="subtle empty-inline">Здесь пока ничего нет.</div>'}</div>${done.length?`<button class="summary-row" data-show-completed style="border:0;width:100%"><span>Сделано сегодня</span><span>${done.length} ›</span></button>`:''}</div></section><aside class="desktop-panel"><div class="card load-card"><div class="section-head"><h2>Общая нагрузка</h2><span class="subtle">На этой неделе</span></div><div class="load-bar"><div class="load-a"></div><div class="load-b"></div></div><div class="load-labels"><div>52%<small>12 дел</small></div><div style="text-align:right">48%<small>11 дел</small></div></div><p class="subtle" style="text-align:center;margin:16px 0 0"><b style="color:var(--ink)">Всё распределено ровно</b><br>Без соревнования и подсчёта победителей.</p></div><div class="card home-note"><div class="eyebrow">О доме</div><h2>Спокойный дом освобождает голову.</h2><p class="subtle">Фокус на том, что требует внимания, а не на том, кто сделал больше.</p></div></aside></div>`)}

function emptyState(){const tomorrow=state.tasks.filter(t=>t.group==='tomorrow'&&!t.completed).slice(0,2);return appFrame(`<div class="row between top-context"><div><div class="eyebrow">${esc(state.homeName)}</div><div class="context-line">На сегодня всё</div></div><button class="icon-btn plus" data-add aria-label="Добавить дело">${ico('plus')}</button></div><div class="empty"><div class="calm-state"><div class="calm-icon">${ico('sparkles')}</div><h2>Всё под контролем.</h2><p>На сегодня дела закрыты. Можно не думать о быте до завтра.</p><div class="calm-meta">${ico('check-circle-2')} Всё сделано</div></div><div class="tomorrow-block"><div class="tomorrow-head"><h3>Завтра</h3><span class="subtle">${tomorrow.length} дела</span></div><div class="task-list">${tomorrow.map(taskRow).join('')}</div></div></div>`)}

function week(){const groups=[['Сегодня','today'],['Завтра','tomorrow'],['Четверг','thu'],['Пятница','fri']];const days=[['Пн','21'],['Вт','22'],['Ср','23'],['Чт','24'],['Пт','25'],['Сб','26'],['Вс','27']];return appFrame(`<div class="row between"><div><h1 class="screen-title">Неделя</h1><div class="subtle">21–27 сентября</div></div><div class="row gap8"><button class="icon-btn" aria-label="Предыдущая неделя">${ico('chevron-left')}</button><button class="icon-btn" aria-label="Следующая неделя">${ico('chevron-right')}</button></div></div><div class="week-strip">${days.map(([d,n],i)=>`<div class="day-pill ${i===1?'active':''}">${d}<b>${n}</b></div>`).join('')}</div><div class="week-progress"><div class="progress-ring"><span>72%</span></div><div><strong>Прогресс за неделю</strong><div class="subtle" style="margin-top:4px">Большая часть домашних дел уже закрыта.</div></div></div>${groups.map(([label,g])=>{const arr=state.tasks.filter(t=>t.group===g&&!t.completed);if(!arr.length)return'';return `<section class="week-group"><div class="week-label"><span>${label}</span><span>${arr.length}</span></div><div class="week-card">${arr.map(taskRow).join('')}</div></section>`}).join('')}`)}

function household(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Дом</h1><p class="subtle">Повторяющиеся дела по зонам.</p></div><button class="icon-btn plus" data-add aria-label="Добавить дело">${ico('plus')}</button></div><div class="household-filter"><button class="mini-tab active">Зоны</button><button class="mini-tab">Рутины</button><button class="mini-tab">Категории</button></div><div class="household-grid rich-grid">${state.routines.map((r,i)=>`<button class="house-card rich-house-card" data-routine="${i}">${categoryArtwork(r.name)}<div class="house-card-copy"><strong>${esc(r.name)}</strong><span>${r.count} ${r.count===1?'дело':r.count<5?'дела':'дел'}</span></div><div class="house-arrow">${ico('chevron-right')}</div></button>`).join('')}</div>`)}

function us(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Мы</h1><p class="subtle">Общая нагрузка, а не соревнование.</p></div><button class="icon-btn" data-notifications aria-label="Уведомления">${ico('bell')}</button></div><div class="us-people"><div class="person-block"><div class="person-ring"><div>А</div></div><div class="person-name"><b>${esc(state.me)}</b><span>52% · 12 дел</span></div></div><div class="heart-orb">${ico('heart')}</div><div class="person-block"><div class="person-ring samring"><div>С</div></div><div class="person-name"><b>${esc(state.partner)}</b><span>48% · 11 дел</span></div></div></div><div class="card load-card"><div class="section-head"><h2>Общая нагрузка</h2><span class="subtle">Эта неделя</span></div><div class="load-bar"><div class="load-a"></div><div class="load-b"></div></div><p class="subtle balance-copy"><b>Всё распределено достаточно ровно.</b><br>Не обязательно 50/50 каждый день — важна общая картина.</p></div><div class="section card settings-card"><button class="setting-row"><span>${ico('house')} <b>Настройки дома</b></span><span>${ico('chevron-right')}</span></button><button class="setting-row" data-notifications><span>${ico('bell')} <b>Уведомления</b></span><span>${ico('chevron-right')}</span></button><button class="setting-row"><span>${ico('repeat-2')} <b>Управление рутинами</b></span><span>${ico('chevron-right')}</span></button><button class="setting-row"><span>${ico('user-plus')} <b>Пригласить партнёра</b></span><span>${ico('chevron-right')}</span></button>${new URLSearchParams(location.search).get('debug')==='1'? `<button class="setting-row danger-row" data-reset><span>${ico('rotate-ccw')} <b>Сбросить демо</b></span><span>${ico('chevron-right')}</span></button>` : ''}</div>`)}

function notifications(){return appFrame(`<div class="row between"><div><h1 class="screen-title">Уведомления</h1><p class="subtle">Только то, что действительно важно.</p></div><button class="icon-btn" data-view="us" aria-label="Закрыть">${ico('x')}</button></div><div class="notification-tabs"><button class="mini-tab active">Все</button><button class="mini-tab">Дела</button><button class="mini-tab">Система</button></div><div class="section card notifications-card">${state.notifications.map((n,i)=>`<div class="notification"><div class="task-icon">${n.icon}</div><div><div class="notification-copy">${esc(n.text)}</div></div><div class="time">${esc(n.time)}</div></div>`).join('')}</div>`)}

function render(){if(!state.onboarded)return renderOnboarding();let body=state.view==='home'?home():state.view==='week'?week():state.view==='household'?household():state.view==='us'?us():notifications();$('#app').innerHTML=body;bind();drawIcons();}
function renderOnboarding(){const steps=[welcomeStep,homeStep,partnerStep,routinesStep];$('#app').innerHTML=steps[state.step]();bindOnboarding();drawIcons()}
function pager(n=0,total=4){return `<div class="pager">${Array.from({length:total},(_,i)=>`<i class="${i===n?'active':''}"></i>`).join('')}</div>`}
function stepbar(n){return `<div class="stepbar">${Array.from({length:3},(_,i)=>`<i class="${i<=n?'active':''}"></i>`).join('')}</div>`}
function welcomeStep(){return `<main class="onboard welcome-screen"><div class="row between"><div class="brand">Together</div><span class="welcome-badge">Для двоих</span></div>${welcomeArtwork()}<div class="eyebrow">Спокойнее жить вместе</div><h1>Дом без лишних<br>напоминаний.</h1><p>Понимайте, что нужно сделать, кто этим занимается и когда можно больше не думать о быте.</p><div class="welcome-proof"><span>${ico('sparkles')} Понятно сегодня</span><span>${ico('users')} Общая нагрузка</span><span>${ico('heart')} Без соревнования</span></div>${pager(0)}<button class="primary" data-next>Начать</button><button data-skip class="text-button">У меня уже есть аккаунт</button></main>`}

function homeStep(){return `<main class="onboard setup-screen"><button class="icon-btn" data-prev aria-label="Назад">${ico('chevron-left')}</button>${stepbar(0)}<div class="setup-symbol">${ico('house-heart')}</div><div class="eyebrow">Ваш общий дом</div><h1 style="font-size:36px">Настроим<br>ваш дом.</h1><p>Сейчас только основное. Всё остальное можно изменить позже.</p><div class="form-stack"><label class="form-label light-label">Название дома</label><div class="input-shell">${ico('house')}<input id="home-name" value="${esc(state.homeName)}" class="field"></div><label class="form-label light-label">Ваше имя</label><div class="input-shell">${ico('user-round')}<input id="me-name" value="${esc(state.me)}" class="field"></div></div><button class="primary" data-save-home>Продолжить</button></main>`}

function partnerStep(){return `<main class="onboard partner-screen"><button class="icon-btn" data-prev aria-label="Назад">${ico('chevron-left')}</button>${stepbar(1)}<div class="pair-visual"><div class="pair-avatar pair-a">А</div><div class="pair-link">${ico('link-2')}</div><div class="pair-avatar pair-s">С</div></div><div class="eyebrow">Пригласите партнёра</div><h1 style="font-size:36px">С кем вы<br>живёте вместе?</h1><p>Партнёр увидит те же домашние дела — без необходимости одному из вас становиться «менеджером дома».</p><div class="invite-card"><div class="invite-icon">${ico('link-2')}</div><div><b>Личная ссылка-приглашение</b><span>together.app/join/abc123</span></div></div><button class="secondary dark-secondary" data-copy style="width:100%">${ico('copy')} Скопировать ссылку</button><button class="secondary share-button" style="width:100%;margin-top:9px">${ico('share-2')} Поделиться…</button><button class="primary" data-next style="margin-top:auto">Продолжить</button></main>`}

function routinesStep(){const opts=[['Посуда','circle-dot'],['Мусор','trash-2'],['Стирка','washing-machine'],['Пылесос','brush-cleaning'],['Ванная','bath'],['Постель','bed-double'],['Продукты','shopping-cart'],['Растения','sprout'],['Питомцы','paw-print']];return `<main class="onboard"><button class="icon-btn" data-prev aria-label="Назад">${ico('chevron-left')}</button>${stepbar(2)}<div class="eyebrow">Начальные рутины</div><h1 style="font-size:34px">Что нужно делать<br>регулярно?</h1><p>Выберите несколько дел для старта. Позже всё можно изменить.</p><div class="routine-grid">${opts.map(([n,i])=>`<button class="routine-opt ${state.routineSelections.includes(n)?'active':''}" data-routine-opt="${n}"><span class="big">${ico(i)}</span>${n}</button>`).join('')}</div><button class="primary" data-finish>Продолжить</button></main>`}

function bind(){$$('[data-view]').forEach(b=>b.onclick=()=>set({view:b.dataset.view}));$$('[data-filter]').forEach(b=>b.onclick=()=>set({filter:b.dataset.filter}));$$('[data-add]').forEach(b=>b.onclick=openAdd);$$('[data-toggle-task]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTask(+b.dataset.toggleTask)});$$('[data-open-task]').forEach(r=>r.onclick=e=>{if(e.target.closest('[data-toggle-task]'))return;openTask(+r.dataset.openTask)});$$('[data-routine]').forEach(r=>r.onclick=()=>openRoutine(+r.dataset.routine));$$('[data-notifications]').forEach(b=>b.onclick=()=>set({view:'notifications'}));const reset=$('[data-reset]');if(reset)reset.onclick=()=>{localStorage.removeItem(STORAGE);state=structuredClone(defaultState);render()};}
function bindOnboarding(){const next=$('[data-next]');if(next)next.onclick=()=>{state.step=Math.min(3,state.step+1);save();render()};const prev=$('[data-prev]');if(prev)prev.onclick=()=>{state.step=Math.max(0,state.step-1);save();render()};const skip=$('[data-skip]');if(skip)skip.onclick=()=>{state.onboarded=true;save();render()};const sh=$('[data-save-home]');if(sh)sh.onclick=()=>{state.homeName=$('#home-name').value.trim()||'Наш дом';state.me=$('#me-name').value.trim()||'Алекс';state.step=2;save();render()};$$('[data-routine-opt]').forEach(b=>b.onclick=()=>{const n=b.dataset.routineOpt;state.routineSelections=state.routineSelections.includes(n)?state.routineSelections.filter(x=>x!==n):[...state.routineSelections,n];save();render()});const fin=$('[data-finish]');if(fin)fin.onclick=()=>{state.onboarded=true;state.view='home';save();render()};const cp=$('[data-copy]');if(cp)cp.onclick=async()=>{try{await navigator.clipboard.writeText('https://together.app/join/abc123');toast('Ссылка скопирована')}catch{toast('Ссылка готова')}}}
function toggleTask(id){state.tasks=state.tasks.map(t=>t.id===id?{...t,completed:!t.completed,overdue:false}:t);save();render();toast(state.tasks.find(t=>t.id===id).completed?'Готово':'Возвращено в работу')}
function openAdd(){showSheet(`<div class="sheet-head"><button class="close" data-close aria-label="Закрыть">${ico('x')}</button><span class="sheet-caption">Новое дело</span></div><h2>Что нужно сделать?</h2><input id="new-title" class="field hero-input" placeholder="Например, купить молоко" autofocus><label class="form-label">Кто делает?</label><div class="choice-grid" id="who"><button class="choice active" data-who="anyone"><b>${ico('users')}</b>Кто угодно</button><button class="choice" data-who="alex"><b>А</b>Я</button><button class="choice" data-who="sam"><b>С</b>Партнёр</button></div><label class="form-label">Когда?</label><div class="choice-grid" id="when"><button class="choice compact active" data-when="today">Сегодня</button><button class="choice compact" data-when="tomorrow">Завтра</button><button class="choice compact" data-when="pick">Выбрать дату</button></div><label class="form-label">Повтор</label><div class="choice-grid"><button class="choice compact active" data-repeat="no">Не повторяется</button><button class="choice compact" data-repeat="weekly">Раз в неделю</button><button class="choice compact" data-repeat="custom">Настроить</button></div><button class="primary create-task-btn" data-create>Добавить дело</button>`);let who='anyone',when='today',repeat='no';$('[data-who]').forEach(b=>b.onclick=()=>{who=b.dataset.who;activateGroup('#who',b)});$('[data-when]').forEach(b=>b.onclick=()=>{when=b.dataset.when;activateGroup('#when',b)});$('[data-repeat]').forEach(b=>b.onclick=()=>{repeat=b.dataset.repeat;$('[data-repeat]').forEach(x=>x.classList.toggle('active',x===b))});$('[data-create]').onclick=()=>{const title=$('#new-title').value.trim();if(!title)return toast('Введите название дела');const id=Math.max(...state.tasks.map(t=>t.id))+1;state.tasks.push({id,title,icon:'✦',assignee:who,due:when==='today'?'Сегодня':when==='tomorrow'?'Завтра':'Скоро',group:when==='tomorrow'?'tomorrow':'today',completed:false,overdue:false,recurring:repeat!=='no',repeat:repeat==='weekly'?'Каждую неделю':repeat==='custom'?'Настраиваемый повтор':'',effort:'Обычная'});save();closeSheet();render();toast('Дело добавлено')}}

function activateGroup(sel,b){$$(sel+' .choice').forEach(x=>x.classList.toggle('active',x===b))}
function openTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;showSheet(`<div class="sheet-head floating-sheet-head"><button class="close" data-close aria-label="Назад">${ico('chevron-left')}</button><button class="close" data-delete="${t.id}" aria-label="Ещё">${ico('more-horizontal')}</button></div>${taskArtwork(t)}<div class="detail-content"><div class="detail-title">${esc(t.title)}</div><div class="detail-pills"><span class="detail-pill">${ico('house')} Дом</span>${t.recurring?'<span class="detail-pill">'+ico('repeat-2')+' Повторяется</span>':''}</div><p class="detail-desc">Видно всем, легко взять на себя и закрыть.</p><div class="detail-group"><div class="detail-row"><div class="detail-row-icon">${ico('calendar-days')}</div><div class="detail-row-copy"><b>Срок</b><small>${esc(t.due)}</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('repeat-2')}</div><div class="detail-row-copy"><b>Повтор</b><small>${esc(t.repeat||'Не повторяется')}</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('gauge')}</div><div class="detail-row-copy"><b>Нагрузка</b><small>${esc(t.effort||'Обычная')}</small></div><span>${ico('chevron-right')}</span></div></div><label class="form-label">Ответственный</label><div class="choice-grid" id="assign"><button class="choice ${t.assignee==='alex'?'active':''}" data-assign="alex"><b>А</b>Вы</button><button class="choice ${t.assignee==='sam'?'active':''}" data-assign="sam"><b>С</b>Сэм</button><button class="choice ${t.assignee==='anyone'?'active':''}" data-assign="anyone"><b>${ico('users')}</b>Кто угодно</button></div>${t.subtasks?.length?`<label class="form-label">Шаги</label><div class="subtask-card">${t.subtasks.map(x=>`<label class="subtask"><input type="checkbox"> <span>${esc(x)}</span></label>`).join('')}</div>`:''}<div class="detail-cta-row"><button class="secondary snooze-btn">${ico('clock-3')} Отложить</button><button class="primary" data-complete-detail>${ico(t.completed?'rotate-ccw':'check')} ${t.completed?'Вернуть':'Готово'}</button></div></div>`);$('[data-assign]').forEach(b=>b.onclick=()=>{t.assignee=b.dataset.assign;save();activateGroup('#assign',b);toast('Ответственный изменён')});$('[data-complete-detail]').onclick=()=>{toggleTask(t.id);closeSheet()};$('[data-delete]').onclick=()=>{if(confirm('Удалить это дело?')){state.tasks=state.tasks.filter(x=>x.id!==t.id);save();closeSheet();render();toast('Дело удалено')}}}

function openRoutine(i){const r=state.routines[i];showSheet(`<div class="sheet-head floating-sheet-head"><button class="close" data-close aria-label="Назад">${ico('chevron-left')}</button><button class="close" aria-label="Ещё">${ico('more-horizontal')}</button></div><div class="detail-cover art-${artTone(r.name)}"><div class="detail-cover-glow"></div><div class="detail-cover-orb">${ico(categoryIconName(r.name))}</div><div class="detail-cover-caption"><span>Рутина</span><b>${r.count} ${r.count===1?'дело':r.count<5?'дела':'дел'}</b></div></div><div class="detail-content"><div class="detail-title">${esc(r.name==='Уборка'?'Убрать ванную':r.name)}</div><div class="detail-pills"><span class="detail-pill">${ico('repeat-2')} Рутина</span><span class="detail-pill">${ico('sparkles')} ${esc(r.name)}</span></div><div class="detail-group"><div class="detail-row"><div class="detail-row-icon">${ico('repeat-2')}</div><div class="detail-row-copy"><b>Повтор</b><small>Каждое воскресенье</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('calendar-days')}</div><div class="detail-row-copy"><b>Следующий срок</b><small>Вс, 27 сентября</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('users')}</div><div class="detail-row-copy"><b>Ответственный</b><small>Кто угодно</small></div><span>${ico('chevron-right')}</span></div><div class="detail-row"><div class="detail-row-icon">${ico('gauge')}</div><div class="detail-row-copy"><b>Нагрузка</b><small>Средняя</small></div><span>${ico('chevron-right')}</span></div></div><div class="notes-card"><span class="subtle">Заметка</span><p>Душ, раковина, туалет и пол.</p></div><button class="primary edit-routine-btn">${ico('pencil')} Изменить рутину</button></div>`)}

function showSheet(html){$('#modal-root').innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true"><div class="grab"></div>${html}</section></div>`;const bd=$('.sheet-backdrop');bd.onclick=e=>{if(e.target===bd)closeSheet()};$('[data-close]').forEach(b=>b.onclick=closeSheet);drawIcons()}
function closeSheet(){$('#modal-root').innerHTML=''}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
